//
// lazy_test.cpp - Test for the lazy Reader / skip API generated by chisel
//
// Copyright (C) 2026 Johan Hedin
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation; either version 2 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

#include <cstdint>
#include <fstream>
#include <iostream>
#include <vector>

#include CHISEL_HEADER
#include CHISEL_LAZY_FILTER

using Root = CHISEL_ROOT;

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "usage: " << argv[0] << " <binary-file>\n";
        return 1;
    }

    std::ifstream f(argv[1], std::ios::binary);
    if (!f) {
        std::cerr << "cannot open: " << argv[1] << '\n';
        return 1;
    }
    const std::vector<uint8_t> buf(std::istreambuf_iterator<char>(f),
                                   std::istreambuf_iterator<char>{});
    f.close();

    const chisel::span<const uint8_t> span{buf.data(), buf.size()};
    std::size_t pos = 0;
    std::size_t total = 0;
    std::size_t matched = 0;

    while (pos < span.size()) {
        const std::size_t rec_start = pos;

        // Lazy path: inspect fields without materialising the whole record.
        bool match = false;
        try {
            auto r = Root::reader(span, pos);
            chisel_test_filter(r, match);
        } catch (const chisel::decode_error& e) {
            std::cerr << "lazy decode error at " << rec_start << ": " << e.what() << '\n';
            return 1;
        }

        const std::size_t lazy_end = pos;

        // Eager path from the same start: verify byte boundary matches.
        std::size_t pos2 = rec_start;
        try {
            Root::decode(span, pos2);
        } catch (const chisel::decode_error& e) {
            std::cerr << "eager decode error at " << rec_start << ": " << e.what() << '\n';
            return 1;
        }

        if (lazy_end != pos2) {
            std::cerr << "byte boundary mismatch at record " << total
                      << ": lazy=" << lazy_end << " eager=" << pos2 << '\n';
            return 1;
        }

        // For matched records: re-decode from raw bytes and print to confirm
        // the captured slice is self-contained.
        if (match) {
            chisel::span<const uint8_t> raw{buf.data() + rec_start, lazy_end - rec_start};
            std::size_t pos3 = 0;
            try {
                auto rec = Root::decode(raw, pos3);
                if (pos3 != raw.size()) {
                    std::cerr << "raw slice decode consumed wrong bytes\n";
                    return 1;
                }
                Root::json_print(std::cout, rec, 4);
                std::cout.put('\n');
            } catch (const chisel::decode_error& e) {
                std::cerr << "raw slice decode error: " << e.what() << '\n';
                return 1;
            }
            ++matched;
        }

        ++total;
    }

    std::cerr << total << " record(s) scanned, " << matched << " matched\n";
    return 0;
}

